### ISSUE TITLE
pooq는 잘 되는데 daum은 오류가 납니다

### ISSUE THREAD

**Issue by jknightw82** [wonipapa/plexutil#2]
안녕하세요~
만들어 주신 다음 에이전트를 잘 쓰고 있습니다.
먼저 감사의 말씀을 드립니다^^
메타 데이터를 정리하다 보니 만들어주신 plexutil로 보완하면 완벽하게 구성이 가능할 것 같아서
사용해 보려고 하는데 daumjson.php를 실행하면 다음과 같은 에러 메시지가 나옵니다
아무래도 이번에 다음 사이트 개편이 있으면서 주소가 바뀌어서 그런 것 같은데
저는 실력이 부족해서 수정할 능력이 안되네요 ㅠ
사용 환경은 시놀로지 6.1버전이고 php7을 깔긴 했는데 정상작동 하지 않아서 수정하라고 하신부분 수정해서 실행은 되는 상태입니다.
아래는 출력되는 에러 메시지입니다.

PHP Warning:  file_get_contents(http://movie.daum.net/tv/series_list.json?tvProgramId=75356&programIds=75356): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /volume2/web/daumjson.php on line 19

Warning: file_get_contents(http://movie.daum.net/tv/series_list.json?tvProgramId=75356&programIds=75356): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /volume2/web/daumjson.php on line 19
PHP Warning:  Invalid argument supplied for foreach() in /volume2/web/daumjson.php on line 31

Warning: Invalid argument supplied for foreach() in /volume2/web/daumjson.php on line 31
PHP Warning:  Invalid argument supplied for foreach() in /volume2/web/daumjson.php on line 42

Warning: Invalid argument supplied for foreach() in /volume2/web/daumjson.php on line 42
PHP Warning:  file_get_contents(http://movie.daum.net/tv/episode?tvProgramId=75356&order=old): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /volume2/web/daumjson.php on line 45

Warning: file_get_contents(http://movie.daum.net/tv/episode?tvProgramId=75356&order=old): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /volume2/web/daumjson.php on line 45

**Comment by wonipapa** [comment]
다음은 수정예정입니다.
